###Introduction to Big Data Final Project

#### **Job Market Analysis Using MapReduce and Apache Spark**

This project analyzes a large job market dataset containing 500,000 rows. The goal is to apply Big Data processing concepts using both MapReduce and Apache Spark.

The project includes:
- MapReduce implementation in Python
- Apache Spark DataFrame workflow
- Data processing and exploratory data analysis
- Optimization techniques
- Optional preparation for machine learning

### **Setup and Data Loading**
In this section, we import the necessary libraries and load the dataset from Google Drive.  
The dataset contains job market information including salaries, experience, occupation, and location.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
from functools import reduce
file_path = '/content/drive/MyDrive/Big Data/job_market_dataset.csv'
df = pd.read_csv(file_path)
print("Dataset loaded successfully.")
print("Shape of the dataset", df.shape)
df.head()

Dataset loaded successfully.
Shape of the dataset (500000, 12)

,country,city,occupation,field,years_of_experience,salary,employment_type,education_level,gender,company_size,year,month
0,Switzerland,Zurich,Operations Manager,Operations,16,359609.0,work_from_home,Master,Male,Large,2023,8
1,India,Bangalore,HR Analyst,Human Resources,12,79059.0,part_time,PhD,Male,Large,2023,5
2,Sweden,Stockholm,Software Engineer,Technology,10,258077.0,freelance,Master,Male,Enterprise,2023,9
3,South Korea,Seoul,Operations Manager,Operations,7,252282.0,part_time,Master,Female,Large,2024,12
4,United States,New York,Cloud Engineer,Technology,4,330618.0,part_time,Master,Male,Enterprise,2022,1

### **Data Understanding**
In this section, we explore the structure of the dataset.  
We examine the schema, preview sample data, and determine the number of rows and columns.  
This step is important to understand the dataset before applying Big Data processing techniques.

In [4]:
#display column names
print("Columns:")
print(df.columns)

#display basic information
print("\nDataset Info:")
df.info()

#display number of rows and columns
print("\nNumber of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Columns:
Index(['country', 'city', 'occupation', 'field', 'years_of_experience',
       'salary', 'employment_type', 'education_level', 'gender',
       'company_size', 'year', 'month'],
      dtype='object')

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   country              500000 non-null  object
 1   city                 500000 non-null  object
 2   occupation           500000 non-null  object
 3   field                500000 non-null  object
 4   years_of_experience  500000 non-null  int64
 5   salary               500000 non-null  float64
 6   employment_type      500000 non-null  object
 7   education_level      500000 non-null  object
 8   gender               500000 non-null  object
 9   company_size         500000 non-null  object
 10  year                 500000 non-null  int64
 11  month                500000 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 45.8+ MB

Number of rows: 500000
Number of columns: 12

###Interpretation
The dataset contains 500,000 rows and 12 columns, making it suitable for Big Data processing. It includes both numerical features (such as salary and years of experience) and categorical features (such as occupation, country and employment type). There are no missing values, which simplifies the data processing step.

###Part 1: **MapReduce Implementation**
The goal of this section is to apply the MapReduce concept using Python.

For this dataset, the MapReduce task is to calculate the average salary for each occupation.


*   The mapper converts each row into a key-value pair: (occupation, salary).
* The shuffle step groups salaries by occupation.
* The reducer calculates the average salary for each occupation.
* Chunk-based processing is simulated to reflect how distributed systems process large datasets.

In [5]:
#select only the columns needed for the MapReduce task
mapreduce_data = df[['occupation', 'salary']]
#preview the selected data
mapreduce_data.head()

           occupation    salary
0  Operations Manager  359609.0
1          HR Analyst   79059.0
2   Software Engineer  258077.0
3  Operations Manager  252282.0
4      Cloud Engineer  330618.0

In [6]:
#Mapper function
#Input: one row from the dataset
#Output: a key-value pair in the form (occupation, salary)
def mapper(row):
  occupation = row['occupation']
  salary = row['salary']
  return (occupation, salary)

In [7]:
#Apply the mapper function using map()
#Each row becomes a key-value pair
mapped_data = list(map(mapper, mapreduce_data.to_dict('records')))
#display first 10 mapped outputs
mapped_data[:10]

[('Operations Manager', 359609.0),
 ('HR Analyst', 79059.0),
 ('Software Engineer', 258077.0),
 ('Operations Manager', 252282.0),
 ('Cloud Engineer', 330618.0),
 ('HR Analyst', 104059.0),
 ('UX Designer', 166377.0),
 ('Marketing Specialist', 188237.0),
 ('Business Analyst', 211953.0),
 ('Business Analyst', 86874.0)]

###Mapper Interpretation
The mapper transforms each row of the dataset into a key-value pair, where the key is the occupation and the value is the salary. This step prepares the data for grouping by occupation in the next phase of the MapReduce process.

In [8]:
from collections import defaultdict
#Shuffle phase: group all salaries by occupation
grouped_data = defaultdict(list)
for occupation, salary in mapped_data:
  grouped_data[occupation].append(salary)
#display first 5 grouped results
list(grouped_data.items())[:5]

[('Operations Manager',
  [359609.0,
   252282.0,
   103021.0,
   226393.0,
   151562.0,
   67783.0,
   206682.0,
   180278.0,
   109221.0,
   208117.0,
   310837.0,
   240435.0,
   185121.0,
   118845.0,
   212428.0,
   251152.0,
   221145.0,
   82869.0,
   195521.0,
   159444.0,
   253519.0,
   255144.0,
   83890.0,
   185432.0,
   198891.0,
   260290.0,
   169672.0,
   215168.0,
   176846.0,
   79630.0,
   243608.0,
   147365.0,
   267518.0,
   191005.0,
   219009.0,
   259281.0,
   284974.0,
   123303.0,
   63763.0,
   108467.0,
   266392.0,
   189795.0,
   157028.0,
   150815.0,
   73150.0,
   169328.0,
   269960.0,
   223344.0,
   206202.0,
   318725.0,
   147549.0,
   180822.0,
   140852.0,
   160396.0,
   136410.0,
   197029.0,
   269471.0,
   298251.0,
   353639.0,
   370000.0,
   370000.0,
   236204.0,
   335586.0,
   206521.0,
   370000.0,
   343281.0,
   370000.0,
   345661.0,
   238825.0,
   329338.0,
   203459.0,
   268230.0,
   225179.0,
   145465.0,
   70865.0,
   251128.0,
   264324.0,
   313674.0,
   311056.0,
   190550.0,
   187179.0,
   370000.0,
   105350.0,
   155797.0,
   316594.0,
   199801.0,
   236741.0,
   177582.0,
   370000.0,
   163401.0,
   138689.0,
   333127.0,
   370000.0,
   212991.0,
   110785.0,
   195827.0,
   171307.0,
   157610.0,
   256179.0,
   271460.0,
   207259.0,
   119520.0,
   174483.0,
   326125.0,
   204814.0,
   165772.0,
   191668.0,
   200095.0,
   238016.0,
   293871.0,
   137093.0,
   351791.0,
   258221.0,
   191689.0,
   262517.0,
   349792.0,
   349824.0,
   309575.0,
   109798.0,
   312700.0,
   194235.0,
   254753.0,
   162206.0,
   66730.0,
   259023.0,
   362532.0,
   319365.0,
   229019.0,
   171712.0,
   18065.0,
   109555.0,
   291146.0,
   154164.0,
   188651.0,
   153297.0,
   121109.0,
   132680.0,
   179855.0,
   138210.0,
   88953.0,
   370000.0,
   80431.0,
   360851.0,
   191814.0,
   305475.0,
   174179.0,
   277418.0,
   360688.0,
   182912.0,
   304877.0,
   173740.0,
   370000.0,
   278403.0,
   232539.0,
   102691.0,
   324443.0,
   242397.0,
   228572.0,
   346493.0,
   220306.0,
   243778.0,
   248257.0,
   297119.0,
   149570.0,
   366262.0,
   221028.0,
   363788.0,
   61330.0,
   151387.0,
   275685.0,
   268919.0,
   208441.0,
   125901.0,
   90559.0,
   175415.0,
   335416.0,
   290115.0,
   279783.0,
   196680.0,
   308574.0,
   145817.0,
   129056.0,
   198079.0,
   140593.0,
   208108.0,
   266514.0,
   72893.0,
   203131.0,
   211146.0,
   132876.0,
   282103.0,
   177029.0,
   52743.0,
   171198.0,
   194899.0,
   271687.0,
   305296.0,
   181501.0,
   195545.0,
   221493.0,
   151639.0,
   226485.0,
   105236.0,
   168630.0,
   186879.0,
   214191.0,
   186408.0,
   351747.0,
   102837.0,
   312224.0,
   206871.0,
   370000.0,
   231059.0,
   141104.0,
   219807.0,
   242324.0,
   339471.0,
   176099.0,
   272996.0,
   127229.0,
   331697.0,
   214973.0,
   250897.0,
   220276.0,
   201630.0,
   127529.0,
   351661.0,
   109787.0,
   103154.0,
   48028.0,
   236327.0,
   273492.0,
   223182.0,
   283280.0,
   28076.0,
   238804.0,
   199388.0,
   145660.0,
   138690.0,
   136958.0,
   301172.0,
   172464.0,
   174937.0,
   142566.0,
   231663.0,
   220462.0,
   215397.0,
   137391.0,
   333797.0,
   200906.0,
   154919.0,
   240617.0,
   271393.0,
   215239.0,
   221021.0,
   54128.0,
   306374.0,
   166619.0,
   181029.0,
   330220.0,
   263289.0,
   232819.0,
   204192.0,
   174557.0,
   237686.0,
   148816.0,
   244306.0,
   336630.0,
   234761.0,
   370000.0,
   67036.0,
   251416.0,
   217242.0,
   102661.0,
   260920.0,
   195753.0,
   219780.0,
   237161.0,
   278117.0,
   218256.0,
   220144.0,
   196579.0,
   214066.0,
   324496.0,
   154455.0,
   78215.0,
   320043.0,
   156840.0,
   254430.0,
   370000.0,
   305371.0,
   239671.0,
   206515.0,
   203540.0,
   206569.0,
   333312.0,
   231743.0,
   127852.0,
   220593.0,
   160386.0,
   147422.0,
   253712.0,
   183400.0,
   267649.0,
   96675.0,
   299366.0,
   242147.0,
   169773.0,
   252155.0,
   313982.0,
   224269.0,
   278986.0,
   263945.0,
   110803.0,
   253629.0,
   325140.0,
   182620.0,
   67917.0,
   134275.0,
   365026.0,
   210783.0,
   134545.0,
   91540.0,
   77617.0,
   191674.0,
   241231.0,
   262314.0,
   158769.0,
   353767.0,
   229022.0,
   217268.0,
   179220.0,
   167389.0,
   273162.0,
   229009.0,
   341250.0,
   276657.0,
   205669.0,
   305976.0,
   107423.0,
   30908.0,
   177274.0,
   140133.0,
   73553.0,
   243043.0,
   286994.0,
   134012.0,
   369256.0,
   177377.0,
   167222.0,
   257112.0,
   240491.0,
   140657.0,
   340722.0,
   252404.0,
   157863.0,
   223240.0,
   243963.0,
   253808.0,
   313958.0,
   303631.0,
   339153.0,
   190552.0,
   180780.0,
   150597.0,
   154178.0,
   207060.0,
   105492.0,
   348186.0,
   172531.0,
   299763.0,
   113140.0,
   123146.0,
   120508.0,
   370000.0,
   271777.0,
   222685.0,
   171539.0,
   216207.0,
   370000.0,
   129206.0,
   169600.0,
   281773.0,
   159428.0,
   221824.0,
   229553.0,
   96898.0,
   209216.0,
   328353.0,
   238477.0,
   232148.0,
   268552.0,
   370000.0,
   187850.0,
   125352.0,
   370000.0,
   240629.0,
   64236.0,
   158594.0,
   210312.0,
   215397.0,
   199710.0,
   170028.0,
   302719.0,
   209575.0,
   347879.0,
   188765.0,
   280447.0,
   239362.0,
   183509.0,
   337867.0,
   154408.0,
   104162.0,
   192871.0,
   305940.0,
   191088.0,
   147299.0,
   224520.0,
   312212.0,
   170610.0,
   280099.0,
   173547.0,
   103795.0,
   111964.0,
   190206.0,
   103698.0,
   141377.0,
   168465.0,
   361384.0,
   202715.0,
   266612.0,
   204473.0,
   121989.0,
   199060.0,
   370000.0,
   264757.0,
   370000.0,
   184765.0,
   211119.0,
   226231.0,
   121871.0,
   151245.0,
   228838.0,
   128511.0,
   166043.0,
   26681.0,
   268363.0,
   179686.0,
   241064.0,
   334729.0,
   195543.0,
   78291.0,
   370000.0,
   353507.0,
   224752.0,
   193795.0,
   108863.0,
   241956.0,
   315721.0,
   260499.0,
   219295.0,
   300972.0,
   95441.0,
   105243.0,
   178404.0,
   254197.0,
   231478.0,
   197005.0,
   199824.0,
   84182.0,
   112963.0,
   280838.0,
   199138.0,
   29506.0,
   123711.0,
   172073.0,
   215853.0,
   125111.0,
   194655.0,
   332094.0,
   153107.0,
   287920.0,
   197740.0,
   225027.0,
   110992.0,
   195927.0,
   175788.0,
   22230.0,
   282548.0,
   364842.0,
   364519.0,
   107898.0,
   259111.0,
   251941.0,
   358244.0,
   283239.0,
   212676.0,
   308446.0,
   180027.0,
   282490.0,
   165349.0,
   262120.0,
   203682.0,
   178719.0,
   95627.0,
   83074.0,
   356405.0,
   315340.0,
   187896.0,
   231274.0,
   204652.0,
   102059.0,
   336446.0,
   135110.0,
   243131.0,
   259377.0,
   221262.0,
   197853.0,
   154992.0,
   349924.0,
   129960.0,
   370000.0,
   244592.0,
   281222.0,
   342239.0,
   205512.0,
   87917.0,
   207359.0,
   352109.0,
   251560.0,
   327232.0,
   286055.0,
   121302.0,
   256151.0,
   260539.0,
   217665.0,
   214911.0,
   207170.0,
   139416.0,
   223058.0,
   17300.0,
   119732.0,
   213303.0,
   352577.0,
   148513.0,
   79188.0,
   159827.0,
   267654.0,
   84073.0,
   134128.0,
   204375.0,
   208129.0,
   141871.0,
   119967.0,
   158599.0,
   353726.0,
   360362.0,
   334088.0,
   250168.0,
   250448.0,
   315198.0,
   292706.0,
   312491.0,
   250632.0,
   211001.0,
   317432.0,
   232351.0,
   205324.0,
   112081.0,
   205181.0,
   312654.0,
   148888.0,
   133153.0,
   162910.0,
   114706.0,
   326663.0,
   304119.0,
   140960.0,
   124018.0,
   342857.0,
   204910.0,
   137277.0,
   271392.0,
   211694.0,
   260620.0,
   233564.0,
   311767.0,
   176212.0,
   40284.0,
   51198.0,
   206875.0,
   148007.0,
   308039.0,
   144445.0,
   268218.0,
   114266.0,
   248369.0,
   321013.0,
   370000.0,
   233439.0,
   225457.0,
   85817.0,
   358015.0,
   281459.0,
   174191.0,
   370000.0,
   164271.0,
   238646.0,
   175868.0,
   167763.0,
   261825.0,
   368378.0,
   263644.0,
   136191.0,
   168450.0,
   349461.0,
   256837.0,
   303175.0,
   319163.0,
   151556.0,
   255380.0,
   370000.0,
   96399.0,
   284540.0,
   179797.0,
   204828.0,
   102690.0,
   152909.0,
   17638.0,
   188612.0,
   287686.0,
   351363.0,
   370000.0,
   298589.0,
   126657.0,
   176714.0,
   351474.0,
   220887.0,
   194955.0,
   128202.0,
   156454.0,
   181335.0,
   90991.0,
   279879.0,
   258662.0,
   200114.0,
   172129.0,
   174292.0,
   194481.0,
   144725.0,
   93622.0,
   302044.0,
   222790.0,
   165456.0,
   293142.0,
   269644.0,
   276710.0,
   143495.0,
   120696.0,
   209035.0,
   253212.0,
   146383.0,
   285867.0,
   224494.0,
   200318.0,
   131388.0,
   148862.0,
   212365.0,
   207156.0,
   322408.0,
   370000.0,
   295089.0,
   370000.0,
   83631.0,
   226783.0,
   160833.0,
   275033.0,
   366915.0,
   289087.0,
   221198.0,
   130834.0,
   257682.0,
   113414.0,
   259640.0,
   143474.0,
   300561.0,
   176028.0,
   228004.0,
   111386.0,
   339368.0,
   227355.0,
   94588.0,
   123021.0,
   206940.0,
   191088.0,
   357661.0,
   219944.0,
   232796.0,
   67362.0,
   264709.0,
   22425.0,
   116142.0,
   125513.0,
   182255.0,
   150234.0,
   254907.0,
   191933.0,
   192434.0,
   176096.0,
   201690.0,
   280516.0,
   109766.0,
   146543.0,
   259284.0,
   234273.0,
   231765.0,
   359519.0,
   246870.0,
   249587.0,
   133605.0,
   202041.0,
   338669.0,
   170260.0,
   213763.0,
   91523.0,
   252874.0,
   187334.0,
   200516.0,
   103884.0,
   151437.0,
   125516.0,
   355971.0,
   247769.0,
   180167.0,
   254845.0,
   215411.0,
   202165.0,
   261345.0,
   266892.0,
   262565.0,
   274848.0,
   306859.0,
   139924.0,
   177199.0,
   213994.0,
   192248.0,
   312206.0,
   166312.0,
   359393.0,
   174158.0,
   149085.0,
   180172.0,
   226000.0,
   236530.0,
   267337.0,
   145846.0,
   241075.0,
   222529.0,
   28523.0,
   112094.0,
   136737.0,
   108100.0,
   83445.0,
   238589.0,
   157195.0,
   180499.0,
   202818.0,
   136385.0,
   347439.0,
   145622.0,
   292259.0,
   101708.0,
   332266.0,
   256710.0,
   292843.0,
   370000.0,
   261424.0,
   185278.0,
   277158.0,
   164735.0,
   115846.0,
   226527.0,
   77919.0,
   202167.0,
   149085.0,
   349846.0,
   185535.0,
   116547.0,
   175411.0,
   261915.0,
   172633.0,
   231546.0,
   370000.0,
   258401.0,
   263848.0,
   275048.0,
   90054.0,
   133534.0,
   243932.0,
   191917.0,
   66145.0,
   154417.0,
   210154.0,
   30211.0,
   236225.0,
   288764.0,
   338976.0,
   82849.0,
   130032.0,
   349598.0,
   99672.0,
   120203.0,
   359029.0,
   370000.0,
   319299.0,
   212120.0,
   207875.0,
   224984.0,
   268489.0,
   147456.0,
   189816.0,
   13945.0,
   165819.0,
   330487.0,
   236884.0,
   167720.0,
   283200.0,
   194899.0,
   158067.0,
   190181.0,
   131569.0,
   77356.0,
   283709.0,
   235170.0,
   144564.0,
   103984.0,
   344178.0,
   278361.0,
   172783.0,
   129767.0,
   211642.0,
   201759.0,
   234535.0,
   299475.0,
   292266.0,
   151188.0,
   204922.0,
   358462.0,
   289000.0,
   86289.0,
   209028.0,
   241575.0,
   212402.0,
   352051.0,
   187516.0,
   284211.0,
   131249.0,
   348236.0,
   247972.0,
   111544.0,
   179654.0,
   130506.0,
   261720.0,
   155162.0,
   321125.0,
   202882.0,
   198796.0,
   136636.0,
   201477.0,
   147643.0,
   268115.0,
   161519.0,
   243850.0,
   265250.0,
   333352.0,
   303655.0,
   316487.0,
   122438.0,
   142253.0,
   217043.0,
   126699.0,
   295303.0,
   285607.0,
   347277.0,
   296969.0,
   103191.0,
   193359.0,
   255089.0,
   192174.0,
   206919.0,
   27800.0,
   259971.0,
   235347.0,
   192299.0,
   203502.0,
   350902.0,
   279430.0,
   242050.0,
   370000.0,
   188122.0,
   370000.0,
   289993.0,
   352227.0,
   278887.0,
   220195.0,
   210539.0,
   370000.0,
   68020.0,
   257945.0,
   157598.0,
   266288.0,
   224981.0,
   126238.0,
   203872.0,
   88092.0,
   330157.0,
   347556.0,
   111743.0,
   221797.0,
   232032.0,
   121427.0,
   161753.0,
   344276.0,
   254629.0,
   245766.0,
   232242.0,
   208357.0,
   334847.0,
   182636.0,
   299008.0,
   167721.0,
   29548.0,
   196287.0,
   351854.0,
   217399.0,
   354561.0,
   208479.0,
   340127.0,
   166268.0,
   96540.0,
   171980.0,
   249524.0,
   204466.0,
   370000.0,
   127113.0,
   248540.0,
   87375.0,
   148899.0,
   335127.0,
   190333.0,
   246148.0,
   76566.0,
   364624.0,
   150537.0,
   220874.0,
   251401.0,
   166425.0,
   127398.0,
   112794.0,
   281568.0,
   150076.0,
   187760.0,
   261069.0,
   227279.0,
   276514.0,
   134717.0,
   359580.0,
   141321.0,
   211610.0,
   348483.0,
   281480.0,
   317204.0,
   159101.0,
   145059.0,
   192832.0,
   331174.0,
   246044.0,
   240287.0,
   140611.0,
   238251.0,
   199615.0,
   92856.0,
   117773.0,
   263364.0,
   75799.0,
   139609.0,
   303811.0,
   152779.0,
   181808.0,
   259404.0,
   114584.0,
   97441.0,
   248337.0,
   176437.0,
   215834.0,
   207965.0,
   323397.0,
   226354.0,
   191820.0,
   192109.0,
   ...]),
 ('HR Analyst',
  [79059.0,
   104059.0,
   129374.0,
   67694.0,
   13576.0,
   72499.0,
   81750.0,
   53222.0,
   230286.0,
   215467.0,
   116653.0,
   193325.0,
   256876.0,
   214509.0,
   92230.0,
   239295.0,
   230407.0,
   36439.0,
   92961.0,
   125970.0,
   197335.0,
   202642.0,
   161781.0,
   144472.0,
   181394.0,
   173333.0,
   100685.0,
   140027.0,
   140343.0,
   115840.0,
   164289.0,
   89143.0,
   252709.0,
   174902.0,
   181725.0,
   207941.0,
   82485.0,
   200149.0,
   20965.0,
   162203.0,
   96462.0,
   113708.0,
   321330.0,
   144882.0,
   132874.0,
   156531.0,
   232082.0,
   165630.0,
   191136.0,
   135334.0,
   155839.0,
   179876.0,
   83251.0,
   95595.0,
   176006.0,
   156427.0,
   60171.0,
   108367.0,
   165728.0,
   161945.0,
   154074.0,
   78556.0,
   187277.0,
   153258.0,
   166202.0,
   112751.0,
   179062.0,
   142444.0,
   185092.0,
   22382.0,
   103287.0,
   132308.0,
   150496.0,
   213249.0,
   95087.0,
   125229.0,
   123675.0,
   150775.0,
   182097.0,
   183854.0,
   192859.0,
   29776.0,
   113569.0,
   157996.0,
   151582.0,
   174742.0,
   142350.0,
   142020.0,
   155427.0,
   169553.0,
   126182.0,
   83656.0,
   146828.0,
   106465.0,
   106663.0,
   162639.0,
   94044.0,
   65007.0,
   189424.0,
   249095.0,
   126447.0,
   82053.0,
   136539.0,
   196983.0,
   152781.0,
   264211.0,
   150150.0,
   355953.0,
   65460.0,
   114463.0,
   251833.0,
   137641.0,
   127574.0,
   42469.0,
   364368.0,
   126677.0,
   110530.0,
   185893.0,
   166423.0,
   188817.0,
   271676.0,
   151168.0,
   229605.0,
   155959.0,
   131130.0,
   141741.0,
   101686.0,
   89775.0,
   137652.0,
   214582.0,
   202325.0,
   242777.0,
   161316.0,
   230378.0,
   117146.0,
   149656.0,
   17668.0,
   169826.0,
   77647.0,
   74367.0,
   78699.0,
   94464.0,
   117649.0,
   209117.0,
   155050.0,
   262585.0,
   74797.0,
   197139.0,
   31326.0,
   264478.0,
   111999.0,
   168462.0,
   42548.0,
   12645.0,
   86337.0,
   151035.0,
   91162.0,
   106600.0,
   129160.0,
   166480.0,
   137294.0,
   123890.0,
   158692.0,
   143044.0,
   101973.0,
   123836.0,
   143561.0,
   100539.0,
   217796.0,
   81541.0,
   321049.0,
   139706.0,
   156204.0,
   147140.0,
   213273.0,
   89007.0,
   171060.0,
   279176.0,
   137144.0,
   85399.0,
   172500.0,
   53418.0,
   70345.0,
   86701.0,
   277033.0,
   76974.0,
   158162.0,
   214709.0,
   161160.0,
   116984.0,
   174306.0,
   150424.0,
   228137.0,
   130225.0,
   150003.0,
   154855.0,
   85584.0,
   133032.0,
   120517.0,
   234869.0,
   16941.0,
   115250.0,
   161458.0,
   177298.0,
   98807.0,
   128217.0,
   124761.0,
   115845.0,
   99114.0,
   156089.0,
   121526.0,
   207905.0,
   151920.0,
   144517.0,
   58012.0,
   210638.0,
   157221.0,
   37828.0,
   122060.0,
   53890.0,
   154001.0,
   195252.0,
   59494.0,
   103128.0,
   125303.0,
   116059.0,
   306174.0,
   108693.0,
   194253.0,
   57347.0,
   173198.0,
   114815.0,
   64078.0,
   125732.0,
   213974.0,
   96689.0,
   95024.0,
   118020.0,
   133056.0,
   149010.0,
   39620.0,
   152814.0,
   118002.0,
   89871.0,
   80195.0,
   163774.0,
   154809.0,
   119519.0,
   221371.0,
   191579.0,
   126681.0,
   86008.0,
   65724.0,
   129232.0,
   132906.0,
   177110.0,
   186593.0,
   142351.0,
   117999.0,
   63539.0,
   110157.0,
   54232.0,
   105567.0,
   127930.0,
   197670.0,
   80723.0,
   70059.0,
   211070.0,
   160360.0,
   197910.0,
   97104.0,
   115687.0,
   171243.0,
   152233.0,
   75813.0,
   135224.0,
   125007.0,
   105775.0,
   109509.0,
   61715.0,
   180035.0,
   192699.0,
   138587.0,
   110232.0,
   219407.0,
   142431.0,
   174961.0,
   211113.0,
   143600.0,
   162328.0,
   130041.0,
   54294.0,
   62703.0,
   158251.0,
   182231.0,
   108522.0,
   75418.0,
   161255.0,
   284482.0,
   214985.0,
   184940.0,
   185397.0,
   91461.0,
   51480.0,
   370000.0,
   169476.0,
   104788.0,
   56772.0,
   106459.0,
   178121.0,
   156106.0,
   85531.0,
   123293.0,
   161149.0,
   160284.0,
   226271.0,
   124414.0,
   154469.0,
   59847.0,
   175074.0,
   252839.0,
   164874.0,
   170689.0,
   67027.0,
   99735.0,
   149933.0,
   188679.0,
   104416.0,
   144195.0,
   28929.0,
   21435.0,
   100366.0,
   156649.0,
   172345.0,
   190044.0,
   226314.0,
   163158.0,
   56069.0,
   115257.0,
   137580.0,
   166687.0,
   190164.0,
   81465.0,
   140624.0,
   118608.0,
   183765.0,
   149227.0,
   98003.0,
   70947.0,
   103271.0,
   69259.0,
   158410.0,
   129650.0,
   85539.0,
   137932.0,
   182741.0,
   114304.0,
   95240.0,
   199256.0,
   234444.0,
   144722.0,
   138783.0,
   230436.0,
   164308.0,
   152308.0,
   99769.0,
   86613.0,
   115486.0,
   270803.0,
   168474.0,
   114508.0,
   158834.0,
   184469.0,
   88289.0,
   103060.0,
   134631.0,
   78407.0,
   87569.0,
   182487.0,
   72458.0,
   119031.0,
   116430.0,
   91290.0,
   184247.0,
   159593.0,
   132576.0,
   43557.0,
   61542.0,
   206759.0,
   57961.0,
   139654.0,
   128650.0,
   131040.0,
   72779.0,
   34290.0,
   145821.0,
   172740.0,
   221657.0,
   303161.0,
   126492.0,
   157380.0,
   165794.0,
   109999.0,
   149584.0,
   138562.0,
   226174.0,
   15187.0,
   149096.0,
   70846.0,
   130787.0,
   33054.0,
   232640.0,
   131877.0,
   85528.0,
   126223.0,
   72102.0,
   62460.0,
   158267.0,
   265618.0,
   189273.0,
   104205.0,
   170604.0,
   112334.0,
   59088.0,
   149494.0,
   173513.0,
   257455.0,
   82691.0,
   137931.0,
   78478.0,
   117201.0,
   131734.0,
   65802.0,
   210246.0,
   163046.0,
   114397.0,
   178427.0,
   164333.0,
   122785.0,
   114682.0,
   104329.0,
   162700.0,
   126119.0,
   209663.0,
   95120.0,
   191947.0,
   189740.0,
   149971.0,
   126298.0,
   143637.0,
   105960.0,
   165200.0,
   190585.0,
   183014.0,
   95144.0,
   213113.0,
   147685.0,
   104493.0,
   162861.0,
   50352.0,
   42370.0,
   97069.0,
   159026.0,
   65785.0,
   79425.0,
   215066.0,
   89441.0,
   87882.0,
   223258.0,
   108606.0,
   111521.0,
   120680.0,
   196630.0,
   219688.0,
   189996.0,
   263373.0,
   102499.0,
   57116.0,
   132491.0,
   65914.0,
   164190.0,
   136140.0,
   187668.0,
   122189.0,
   69799.0,
   46633.0,
   211537.0,
   125703.0,
   160657.0,
   211250.0,
   63242.0,
   98315.0,
   104471.0,
   43222.0,
   86269.0,
   237875.0,
   120715.0,
   91771.0,
   282335.0,
   48516.0,
   206414.0,
   62995.0,
   69301.0,
   75248.0,
   247962.0,
   65727.0,
   232895.0,
   210455.0,
   175391.0,
   206839.0,
   217359.0,
   182542.0,
   67486.0,
   176831.0,
   98788.0,
   209794.0,
   84530.0,
   219924.0,
   155358.0,
   78518.0,
   231368.0,
   153673.0,
   129483.0,
   135129.0,
   130344.0,
   172716.0,
   107742.0,
   233664.0,
   93279.0,
   100507.0,
   173914.0,
   217921.0,
   361382.0,
   168013.0,
   239755.0,
   164603.0,
   181063.0,
   181833.0,
   57159.0,
   145910.0,
   107421.0,
   141118.0,
   163957.0,
   155762.0,
   210946.0,
   175000.0,
   185684.0,
   150305.0,
   162473.0,
   218677.0,
   81930.0,

###Shuffle Phase Interpretation
The shuffle phase groups all salary values by occupation. This means that every occupation now has a list of salaries connected to it. This step is necessary before applying the reducer, because the reducer needs all values for the same key in order to calculate the average salary.

In [9]:
#Reducer function
#Input: one occupation and its list of salaries
#Output: occupation and average salary
def reducer(item):
  occupation, salaries = item
  average_salary = sum(salaries) / len(salaries)
  return (occupation, average_salary)

In [10]:
#Apply reducer to grouped data
reduced_data = list(map(reducer, grouped_data.items()))
#display first 10 reduced results
reduced_data[:10]

[('Operations Manager', 213451.235518732),
 ('HR Analyst', 144604.00033688667),
 ('Software Engineer', 223677.86047125445),
 ('Cloud Engineer', 242826.7555763195),
 ('UX Designer', 192173.97958988577),
 ('Marketing Specialist', 156345.1849212845),
 ('Business Analyst', 191619.7314657886),
 ('Financial Analyst', 202585.41912186722),
 ('Data Scientist', 233261.97111748127),
 ('Data Analyst', 179691.18065597318)]

### Reducer Interpretation
The reducer calculates the average salary for each occupation by summing all salaries for that occupation and dividing by the number of records. The output shows each occupation with its average salary, which helps identify salary differences between job roles.

In [11]:
#sort occupations by average salary in descending order
sorted_mapreduce_results = sorted(reduced_data, key=lambda x: x[1], reverse=True)
#display top 10 highest-paying occupations
sorted_mapreduce_results[:10]

[('AI Engineer', 252158.15810768752),
 ('Product Manager', 251276.937323708),
 ('Cloud Engineer', 242826.7555763195),
 ('Data Scientist', 233261.97111748127),
 ('Software Engineer', 223677.86047125445),
 ('Operations Manager', 213451.235518732),
 ('Financial Analyst', 202585.41912186722),
 ('UX Designer', 192173.97958988577),
 ('Business Analyst', 191619.7314657886),
 ('Data Analyst', 179691.18065597318)]

### MapReduce Results Interpretation
The results show the top-paying occupations based on average salary.

Roles such as AI Engineer, Product Manager and Cloud Engineer have the highest average salaries, indicating that technical and specialized roles tend to be more highly compensated.

This analysis highlights how salary levels vary significantly depending on the occupation, with data-related and enginnering roles among the highest paying.

### MapReduce Explanation
The mapper function processes each row of the dataset and produces key-value pairs in the form (occupation, salary).
During the shuffle phase, all values associated with the same key (occupation) are grouped together.
The reducer then aggregates these values by calculating the average salary for each occupation.
This process demonstrates how large datasets can be processed efficiently by dividing tasks into smaller steps and combining results.

### **Chunk-Based Processing with 'functools.reduce()'**
To better simulate distributed Big Data processing, the dataset is divided into smaller chunks. Each chunk is processed seperately using the mapper logic, similar to how different machines process parts of a dataset in a distributed system.

The 'functools.reduce()' function is then used to combine the partial grouped results from all chunks into one final grouped dataset.

In [12]:
chunk_size = 50000
chunks = [
    mapreduce_data[i:i + chunk_size]
    for i in range(0, len(mapreduce_data), chunk_size)
]
print("Number of chunks:", len(chunks))

Number of chunks: 10

In [13]:
#Process each chunk seperately
def process_chunk(chunk):
  mapped = list(map(mapper, chunk.to_dict('records')))
  #shuffle phase per chunk
  local_group = {}
  for occupation, salary in mapped:
    if occupation not in local_group:
      local_group[occupation] = []
    local_group[occupation].append(salary)
  return local_group
#apply to all chunks
chunk_results = list(map(process_chunk, chunks))
len(chunk_results)

10

### Chunk Processing Interpretation
Each chunk is processed independently using the mapper and local grouping logic. This simulates how distributed systems divide large datasets into smaller parts and process them in parallel across multiple machines.

In [14]:
def merge_groups(group1, group2):
  for occupation, salaries in group2.items():
    if occupation not in group1:
      group1[occupation] = []
    group1[occupation].extend(salaries)
  return group1
#combine all chunk results
final_grouped_data = reduce(merge_groups, chunk_results)
list(final_grouped_data.items())[:5]

[('Operations Manager',
  [359609.0,
   252282.0,
   103021.0,
   226393.0,
   151562.0,
   67783.0,
   206682.0,
   180278.0,
   109221.0,
   208117.0,
   310837.0,
   240435.0,
   185121.0,
   118845.0,
   212428.0,
   251152.0,
   221145.0,
   82869.0,
   195521.0,
   159444.0,
   253519.0,
   255144.0,
   83890.0,
   185432.0,
   198891.0,
   260290.0,
   169672.0,
   215168.0,
   176846.0,
   79630.0,
   243608.0,
   147365.0,
   267518.0,
   191005.0,
   219009.0,
   259281.0,
   284974.0,
   123303.0,
   63763.0,
   108467.0,
   266392.0,
   189795.0,
   157028.0,
   150815.0,
   73150.0,
   169328.0,
   269960.0,
   223344.0,
   206202.0,
   318725.0,
   147549.0,
   180822.0,
   140852.0,
   160396.0,
   136410.0,
   197029.0,
   269471.0,
   298251.0,
   353639.0,
   370000.0,
   370000.0,
   236204.0,
   335586.0,
   206521.0,
   370000.0,
   343281.0,
   370000.0,
   345661.0,
   238825.0,
   329338.0,
   203459.0,
   268230.0,
   225179.0,
   145465.0,
   70865.0,
   251128.0,
   264324.0,
   313674.0,
   311056.0,
   190550.0,
   187179.0,
   370000.0,
   105350.0,
   155797.0,
   316594.0,
   199801.0,
   236741.0,
   177582.0,
   370000.0,
   163401.0,
   138689.0,
   333127.0,
   370000.0,
   212991.0,
   110785.0,
   195827.0,
   171307.0,
   157610.0,
   256179.0,
   271460.0,
   207259.0,
   119520.0,
   174483.0,
   326125.0,
   204814.0,
   165772.0,
   191668.0,
   200095.0,
   238016.0,
   293871.0,
   137093.0,
   351791.0,
   258221.0,
   191689.0,
   262517.0,
   349792.0,
   349824.0,
   309575.0,
   109798.0,
   312700.0,
   194235.0,
   254753.0,
   162206.0,
   66730.0,
   259023.0,
   362532.0,
   319365.0,
   229019.0,
   171712.0,
   18065.0,
   109555.0,
   291146.0,
   154164.0,
   188651.0,
   153297.0,
   121109.0,
   132680.0,
   179855.0,
   138210.0,
   88953.0,
   370000.0,
   80431.0,
   360851.0,
   191814.0,
   305475.0,
   174179.0,
   277418.0,
   360688.0,
   182912.0,
   304877.0,
   173740.0,
   370000.0,
   278403.0,
   232539.0,
   102691.0,
   324443.0,
   242397.0,
   228572.0,
   346493.0,
   220306.0,
   243778.0,
   248257.0,
   297119.0,
   149570.0,
   366262.0,
   221028.0,
   363788.0,
   61330.0,
   151387.0,
   275685.0,
   268919.0,
   208441.0,
   125901.0,
   90559.0,
   175415.0,
   335416.0,
   290115.0,
   279783.0,
   196680.0,
   308574.0,
   145817.0,
   129056.0,
   198079.0,
   140593.0,
   208108.0,
   266514.0,
   72893.0,
   203131.0,
   211146.0,
   132876.0,
   282103.0,
   177029.0,
   52743.0,
   171198.0,
   194899.0,
   271687.0,
   305296.0,
   181501.0,
   195545.0,
   221493.0,
   151639.0,
   226485.0,
   105236.0,
   168630.0,
   186879.0,
   214191.0,
   186408.0,
   351747.0,
   102837.0,
   312224.0,
   206871.0,
   370000.0,
   231059.0,
   141104.0,
   219807.0,
   242324.0,
   339471.0,
   176099.0,
   272996.0,
   127229.0,
   331697.0,
   214973.0,
   250897.0,
   220276.0,
   201630.0,
   127529.0,
   351661.0,
   109787.0,
   103154.0,
   48028.0,
   236327.0,
   273492.0,
   223182.0,
   283280.0,
   28076.0,
   238804.0,
   199388.0,
   145660.0,
   138690.0,
   136958.0,
   301172.0,
   172464.0,
   174937.0,
   142566.0,
   231663.0,
   220462.0,
   215397.0,
   137391.0,
   333797.0,
   200906.0,
   154919.0,
   240617.0,
   271393.0,
   215239.0,
   221021.0,
   54128.0,
   306374.0,
   166619.0,
   181029.0,
   330220.0,
   263289.0,
   232819.0,
   204192.0,
   174557.0,
   237686.0,
   148816.0,
   244306.0,
   336630.0,
   234761.0,
   370000.0,
   67036.0,
   251416.0,
   217242.0,
   102661.0,
   260920.0,
   195753.0,
   219780.0,
   237161.0,
   278117.0,
   218256.0,
   220144.0,
   196579.0,
   214066.0,
   324496.0,
   154455.0,
   78215.0,
   320043.0,
   156840.0,
   254430.0,
   370000.0,
   305371.0,
   239671.0,
   206515.0,
   203540.0,
   206569.0,
   333312.0,
   231743.0,
   127852.0,
   220593.0,
   160386.0,
   147422.0,
   253712.0,
   183400.0,
   267649.0,
   96675.0,
   299366.0,
   242147.0,
   169773.0,
   252155.0,
   313982.0,
   224269.0,
   278986.0,
   263945.0,
   110803.0,
   253629.0,
   325140.0,
   182620.0,
   67917.0,
   134275.0,
   365026.0,
   210783.0,
   134545.0,
   91540.0,
   77617.0,
   191674.0,
   241231.0,
   262314.0,
   158769.0,
   353767.0,
   229022.0,
   217268.0,
   179220.0,
   167389.0,
   273162.0,
   229009.0,
   341250.0,
   276657.0,
   205669.0,
   305976.0,
   107423.0,
   30908.0,
   177274.0,
   140133.0,
   73553.0,
   243043.0,
   286994.0,
   134012.0,
   369256.0,
   177377.0,
   167222.0,
   257112.0,
   240491.0,
   140657.0,
   340722.0,
   252404.0,
   157863.0,
   223240.0,
   243963.0,
   253808.0,
   313958.0,
   303631.0,
   339153.0,
   190552.0,
   180780.0,
   150597.0,
   154178.0,
   207060.0,
   105492.0,
   348186.0,
   172531.0,
   299763.0,
   113140.0,
   123146.0,
   120508.0,
   370000.0,
   271777.0,
   222685.0,
   171539.0,
   216207.0,
   370000.0,
   129206.0,
   169600.0,
   281773.0,
   159428.0,
   221824.0,
   229553.0,
   96898.0,
   209216.0,
   328353.0,
   238477.0,
   232148.0,
   268552.0,
   370000.0,
   187850.0,
   125352.0,
   370000.0,
   240629.0,
   64236.0,
   158594.0,
   210312.0,
   215397.0,
   199710.0,
   170028.0,
   302719.0,
   209575.0,
   347879.0,
   188765.0,
   280447.0,
   239362.0,
   183509.0,
   337867.0,
   154408.0,
   104162.0,
   192871.0,
   305940.0,
   191088.0,
   147299.0,
   224520.0,
   312212.0,
   170610.0,
   280099.0,
   173547.0,
   103795.0,
   111964.0,
   190206.0,
   103698.0,
   141377.0,
   168465.0,
   361384.0,
   202715.0,
   266612.0,
   204473.0,
   121989.0,
   199060.0,
   370000.0,
   264757.0,
   370000.0,
   184765.0,
   211119.0,
   226231.0,
   121871.0,
   151245.0,
   228838.0,
   128511.0,
   166043.0,
   26681.0,
   268363.0,
   179686.0,
   241064.0,
   334729.0,
   195543.0,
   78291.0,
   370000.0,
   353507.0,
   224752.0,
   193795.0,
   108863.0,
   241956.0,
   315721.0,
   260499.0,
   219295.0,
   300972.0,
   95441.0,
   105243.0,
   178404.0,
   254197.0,
   231478.0,
   197005.0,
   199824.0,
   84182.0,
   112963.0,
   280838.0,
   199138.0,
   29506.0,
   123711.0,
   172073.0,
   215853.0,
   125111.0,
   194655.0,
   332094.0,
   153107.0,
   287920.0,
   197740.0,
   225027.0,
   110992.0,
   195927.0,
   175788.0,
   22230.0,
   282548.0,
   364842.0,
   364519.0,
   107898.0,
   259111.0,
   251941.0,
   358244.0,
   283239.0,
   212676.0,
   308446.0,
   180027.0,
   282490.0,
   165349.0,
   262120.0,
   203682.0,
   178719.0,
   95627.0,
   83074.0,
   356405.0,
   315340.0,
   187896.0,
   231274.0,
   204652.0,
   102059.0,
   336446.0,
   135110.0,
   243131.0,
   259377.0,
   221262.0,
   197853.0,
   154992.0,
   349924.0,
   129960.0,
   370000.0,
   244592.0,
   281222.0,
   342239.0,
   205512.0,
   87917.0,
   207359.0,
   352109.0,
   251560.0,
   327232.0,
   286055.0,
   121302.0,
   256151.0,
   260539.0,
   217665.0,
   214911.0,
   207170.0,
   139416.0,
   223058.0,
   17300.0,
   119732.0,
   213303.0,
   352577.0,
   148513.0,
   79188.0,
   159827.0,
   267654.0,
   84073.0,
   134128.0,
   204375.0,
   208129.0,
   141871.0,
   119967.0,
   158599.0,
   353726.0,
   360362.0,
   334088.0,
   250168.0,
   250448.0,
   315198.0,
   292706.0,
   312491.0,
   250632.0,
   211001.0,
   317432.0,
   232351.0,
   205324.0,
   112081.0,
   205181.0,
   312654.0,
   148888.0,
   133153.0,
   162910.0,
   114706.0,
   326663.0,
   304119.0,
   140960.0,
   124018.0,
   342857.0,
   204910.0,
   137277.0,
   271392.0,
   211694.0,
   260620.0,
   233564.0,
   311767.0,
   176212.0,
   40284.0,
   51198.0,
   206875.0,
   148007.0,
   308039.0,
   144445.0,
   268218.0,
   114266.0,
   248369.0,
   321013.0,
   370000.0,
   233439.0,
   225457.0,
   85817.0,
   358015.0,
   281459.0,
   174191.0,
   370000.0,
   164271.0,
   238646.0,
   175868.0,
   167763.0,
   261825.0,
   368378.0,
   263644.0,
   136191.0,
   168450.0,
   349461.0,
   256837.0,
   303175.0,
   319163.0,
   151556.0,
   255380.0,
   370000.0,
   96399.0,
   284540.0,
   179797.0,
   204828.0,
   102690.0,
   152909.0,
   17638.0,
   188612.0,
   287686.0,
   351363.0,
   370000.0,
   298589.0,
   126657.0,
   176714.0,
   351474.0,
   220887.0,
   194955.0,
   128202.0,
   156454.0,
   181335.0,
   90991.0,
   279879.0,
   258662.0,
   200114.0,
   172129.0,
   174292.0,
   194481.0,
   144725.0,
   93622.0,
   302044.0,
   222790.0,
   165456.0,
   293142.0,
   269644.0,
   276710.0,
   143495.0,
   120696.0,
   209035.0,
   253212.0,
   146383.0,
   285867.0,
   224494.0,
   200318.0,
   131388.0,
   148862.0,
   212365.0,
   207156.0,
   322408.0,
   370000.0,
   295089.0,
   370000.0,
   83631.0,
   226783.0,
   160833.0,
   275033.0,
   366915.0,
   289087.0,
   221198.0,
   130834.0,
   257682.0,
   113414.0,
   259640.0,
   143474.0,
   300561.0,
   176028.0,
   228004.0,
   111386.0,
   339368.0,
   227355.0,
   94588.0,
   123021.0,
   206940.0,
   191088.0,
   357661.0,
   219944.0,
   232796.0,
   67362.0,
   264709.0,
   22425.0,
   116142.0,
   125513.0,
   182255.0,
   150234.0,
   254907.0,
   191933.0,
   192434.0,
   176096.0,
   201690.0,
   280516.0,
   109766.0,
   146543.0,
   259284.0,
   234273.0,
   231765.0,
   359519.0,
   246870.0,
   249587.0,
   133605.0,
   202041.0,
   338669.0,
   170260.0,
   213763.0,
   91523.0,
   252874.0,
   187334.0,
   200516.0,
   103884.0,
   151437.0,
   125516.0,
   355971.0,
   247769.0,
   180167.0,
   254845.0,
   215411.0,
   202165.0,
   261345.0,
   266892.0,
   262565.0,
   274848.0,
   306859.0,
   139924.0,
   177199.0,
   213994.0,
   192248.0,
   312206.0,
   166312.0,
   359393.0,
   174158.0,
   149085.0,
   180172.0,
   226000.0,
   236530.0,
   267337.0,
   145846.0,
   241075.0,
   222529.0,
   28523.0,
   112094.0,
   136737.0,
   108100.0,
   83445.0,
   238589.0,
   157195.0,
   180499.0,
   202818.0,
   136385.0,
   347439.0,
   145622.0,
   292259.0,
   101708.0,
   332266.0,
   256710.0,
   292843.0,
   370000.0,
   261424.0,
   185278.0,
   277158.0,
   164735.0,
   115846.0,
   226527.0,
   77919.0,
   202167.0,
   149085.0,
   349846.0,
   185535.0,
   116547.0,
   175411.0,
   261915.0,
   172633.0,
   231546.0,
   370000.0,
   258401.0,
   263848.0,
   275048.0,
   90054.0,
   133534.0,
   243932.0,
   191917.0,
   66145.0,
   154417.0,
   210154.0,
   30211.0,
   236225.0,
   288764.0,
   338976.0,
   82849.0,
   130032.0,
   349598.0,
   99672.0,
   120203.0,
   359029.0,
   370000.0,
   319299.0,
   212120.0,
   207875.0,
   224984.0,
   268489.0,
   147456.0,
   189816.0,
   13945.0,
   165819.0,
   330487.0,
   236884.0,
   167720.0,
   283200.0,
   194899.0,
   158067.0,
   190181.0,
   131569.0,
   77356.0,
   283709.0,
   235170.0,
   144564.0,
   103984.0,
   344178.0,
   278361.0,
   172783.0,
   129767.0,
   211642.0,
   201759.0,
   234535.0,
   299475.0,
   292266.0,
   151188.0,
   204922.0,
   358462.0,
   289000.0,
   86289.0,
   209028.0,
   241575.0,
   212402.0,
   352051.0,
   187516.0,
   284211.0,
   131249.0,
   348236.0,
   247972.0,
   111544.0,
   179654.0,
   130506.0,
   261720.0,
   155162.0,
   321125.0,
   202882.0,
   198796.0,
   136636.0,
   201477.0,
   147643.0,
   268115.0,
   161519.0,
   243850.0,
   265250.0,
   333352.0,
   303655.0,
   316487.0,
   122438.0,
   142253.0,
   217043.0,
   126699.0,
   295303.0,
   285607.0,
   347277.0,
   296969.0,
   103191.0,
   193359.0,
   255089.0,
   192174.0,
   206919.0,
   27800.0,
   259971.0,
   235347.0,
   192299.0,
   203502.0,
   350902.0,
   279430.0,
   242050.0,
   370000.0,
   188122.0,
   370000.0,
   289993.0,
   352227.0,
   278887.0,
   220195.0,
   210539.0,
   370000.0,
   68020.0,
   257945.0,
   157598.0,
   266288.0,
   224981.0,
   126238.0,
   203872.0,
   88092.0,
   330157.0,
   347556.0,
   111743.0,
   221797.0,
   232032.0,
   121427.0,
   161753.0,
   344276.0,
   254629.0,
   245766.0,
   232242.0,
   208357.0,
   334847.0,
   182636.0,
   299008.0,
   167721.0,
   29548.0,
   196287.0,
   351854.0,
   217399.0,
   354561.0,
   208479.0,
   340127.0,
   166268.0,
   96540.0,
   171980.0,
   249524.0,
   204466.0,
   370000.0,
   127113.0,
   248540.0,
   87375.0,
   148899.0,
   335127.0,
   190333.0,
   246148.0,
   76566.0,
   364624.0,
   150537.0,
   220874.0,
   251401.0,
   166425.0,
   127398.0,
   112794.0,
   281568.0,
   150076.0,
   187760.0,
   261069.0,
   227279.0,
   276514.0,
   134717.0,
   359580.0,
   141321.0,
   211610.0,
   348483.0,
   281480.0,
   317204.0,
   159101.0,
   145059.0,
   192832.0,
   331174.0,
   246044.0,
   240287.0,
   140611.0,
   238251.0,
   199615.0,
   92856.0,
   117773.0,
   263364.0,
   75799.0,
   139609.0,
   303811.0,
   152779.0,
   181808.0,
   259404.0,
   114584.0,
   97441.0,
   248337.0,
   176437.0,
   215834.0,
   207965.0,
   323397.0,
   226354.0,
   191820.0,
   192109.0,
   ...]),
 ('HR Analyst',
  [79059.0,
   104059.0,
   129374.0,
   67694.0,
   13576.0,
   72499.0,
   81750.0,
   53222.0,
   230286.0,
   215467.0,
   116653.0,
   193325.0,
   256876.0,
   214509.0,
   92230.0,
   239295.0,
   230407.0,
   36439.0,
   92961.0,
   125970.0,
   197335.0,
   202642.0,
   161781.0,
   144472.0,
   181394.0,
   173333.0,
   100685.0,
   140027.0,
   140343.0,
   115840.0,
   164289.0,
   89143.0,
   252709.0,
   174902.0,
   181725.0,
   207941.0,
   82485.0,
   200149.0,
   20965.0,
   162203.0,
   96462.0,
   113708.0,
   321330.0,
   144882.0,
   132874.0,
   156531.0,
   232082.0,
   165630.0,
   191136.0,
   135334.0,
   155839.0,
   179876.0,
   83251.0,
   95595.0,
   176006.0,
   156427.0,
   60171.0,
   108367.0,
   165728.0,
   161945.0,
   154074.0,
   78556.0,
   187277.0,
   153258.0,
   166202.0,
   112751.0,
   179062.0,
   142444.0,
   185092.0,
   22382.0,
   103287.0,
   132308.0,
   150496.0,
   213249.0,
   95087.0,
   125229.0,
   123675.0,
   150775.0,
   182097.0,
   183854.0,
   192859.0,
   29776.0,
   113569.0,
   157996.0,
   151582.0,
   174742.0,
   142350.0,
   142020.0,
   155427.0,
   169553.0,
   126182.0,
   83656.0,
   146828.0,
   106465.0,
   106663.0,
   162639.0,
   94044.0,
   65007.0,
   189424.0,
   249095.0,
   126447.0,
   82053.0,
   136539.0,
   196983.0,
   152781.0,
   264211.0,
   150150.0,
   355953.0,
   65460.0,
   114463.0,
   251833.0,
   137641.0,
   127574.0,
   42469.0,
   364368.0,
   126677.0,
   110530.0,
   185893.0,
   166423.0,
   188817.0,
   271676.0,
   151168.0,
   229605.0,
   155959.0,
   131130.0,
   141741.0,
   101686.0,
   89775.0,
   137652.0,
   214582.0,
   202325.0,
   242777.0,
   161316.0,
   230378.0,
   117146.0,
   149656.0,
   17668.0,
   169826.0,
   77647.0,
   74367.0,
   78699.0,
   94464.0,
   117649.0,
   209117.0,
   155050.0,
   262585.0,
   74797.0,
   197139.0,
   31326.0,
   264478.0,
   111999.0,
   168462.0,
   42548.0,
   12645.0,
   86337.0,
   151035.0,
   91162.0,
   106600.0,
   129160.0,
   166480.0,
   137294.0,
   123890.0,
   158692.0,
   143044.0,
   101973.0,
   123836.0,
   143561.0,
   100539.0,
   217796.0,
   81541.0,
   321049.0,
   139706.0,
   156204.0,
   147140.0,
   213273.0,
   89007.0,
   171060.0,
   279176.0,
   137144.0,
   85399.0,
   172500.0,
   53418.0,
   70345.0,
   86701.0,
   277033.0,
   76974.0,
   158162.0,
   214709.0,
   161160.0,
   116984.0,
   174306.0,
   150424.0,
   228137.0,
   130225.0,
   150003.0,
   154855.0,
   85584.0,
   133032.0,
   120517.0,
   234869.0,
   16941.0,
   115250.0,
   161458.0,
   177298.0,
   98807.0,
   128217.0,
   124761.0,
   115845.0,
   99114.0,
   156089.0,
   121526.0,
   207905.0,
   151920.0,
   144517.0,
   58012.0,
   210638.0,
   157221.0,
   37828.0,
   122060.0,
   53890.0,
   154001.0,
   195252.0,
   59494.0,
   103128.0,
   125303.0,
   116059.0,
   306174.0,
   108693.0,
   194253.0,
   57347.0,
   173198.0,
   114815.0,
   64078.0,
   125732.0,
   213974.0,
   96689.0,
   95024.0,
   118020.0,
   133056.0,
   149010.0,
   39620.0,
   152814.0,
   118002.0,
   89871.0,
   80195.0,
   163774.0,
   154809.0,
   119519.0,
   221371.0,
   191579.0,
   126681.0,
   86008.0,
   65724.0,
   129232.0,
   132906.0,
   177110.0,
   186593.0,
   142351.0,
   117999.0,
   63539.0,
   110157.0,
   54232.0,
   105567.0,
   127930.0,
   197670.0,
   80723.0,
   70059.0,
   211070.0,
   160360.0,
   197910.0,
   97104.0,
   115687.0,
   171243.0,
   152233.0,
   75813.0,
   135224.0,
   125007.0,
   105775.0,
   109509.0,
   61715.0,
   180035.0,
   192699.0,
   138587.0,
   110232.0,
   219407.0,
   142431.0,
   174961.0,
   211113.0,
   143600.0,
   162328.0,
   130041.0,
   54294.0,
   62703.0,
   158251.0,
   182231.0,
   108522.0,
   75418.0,
   161255.0,
   284482.0,
   214985.0,
   184940.0,
   185397.0,
   91461.0,
   51480.0,
   370000.0,
   169476.0,
   104788.0,
   56772.0,
   106459.0,
   178121.0,
   156106.0,
   85531.0,
   123293.0,
   161149.0,
   160284.0,
   226271.0,
   124414.0,
   154469.0,
   59847.0,
   175074.0,
   252839.0,
   164874.0,
   170689.0,
   67027.0,
   99735.0,
   149933.0,
   188679.0,
   104416.0,
   144195.0,
   28929.0,
   21435.0,
   100366.0,
   156649.0,
   172345.0,
   190044.0,
   226314.0,
   163158.0,
   56069.0,
   115257.0,
   137580.0,
   166687.0,
   190164.0,
   81465.0,
   140624.0,
   118608.0,
   183765.0,
   149227.0,
   98003.0,
   70947.0,
   103271.0,
   69259.0,
   158410.0,
   129650.0,
   85539.0,
   137932.0,
   182741.0,
   114304.0,
   95240.0,
   199256.0,
   234444.0,
   144722.0,
   138783.0,
   230436.0,
   164308.0,
   152308.0,
   99769.0,
   86613.0,
   115486.0,
   270803.0,
   168474.0,
   114508.0,
   158834.0,
   184469.0,
   88289.0,
   103060.0,
   134631.0,
   78407.0,
   87569.0,
   182487.0,
   72458.0,
   119031.0,
   116430.0,
   91290.0,
   184247.0,
   159593.0,
   132576.0,
   43557.0,
   61542.0,
   206759.0,
   57961.0,
   139654.0,
   128650.0,
   131040.0,
   72779.0,
   34290.0,
   145821.0,
   172740.0,
   221657.0,
   303161.0,
   126492.0,
   157380.0,
   165794.0,
   109999.0,
   149584.0,
   138562.0,
   226174.0,
   15187.0,
   149096.0,
   70846.0,
   130787.0,
   33054.0,
   232640.0,
   131877.0,
   85528.0,
   126223.0,
   72102.0,
   62460.0,
   158267.0,
   265618.0,
   189273.0,
   104205.0,
   170604.0,
   112334.0,
   59088.0,
   149494.0,
   173513.0,
   257455.0,
   82691.0,
   137931.0,
   78478.0,
   117201.0,
   131734.0,
   65802.0,
   210246.0,
   163046.0,
   114397.0,
   178427.0,
   164333.0,
   122785.0,
   114682.0,
   104329.0,
   162700.0,
   126119.0,
   209663.0,
   95120.0,
   191947.0,
   189740.0,
   149971.0,
   126298.0,
   143637.0,
   105960.0,
   165200.0,
   190585.0,
   183014.0,
   95144.0,
   213113.0,
   147685.0,
   104493.0,
   162861.0,
   50352.0,
   42370.0,
   97069.0,
   159026.0,
   65785.0,
   79425.0,
   215066.0,
   89441.0,
   87882.0,
   223258.0,
   108606.0,
   111521.0,
   120680.0,
   196630.0,
   219688.0,
   189996.0,
   263373.0,
   102499.0,
   57116.0,
   132491.0,
   65914.0,
   164190.0,
   136140.0,
   187668.0,
   122189.0,
   69799.0,
   46633.0,
   211537.0,
   125703.0,
   160657.0,
   211250.0,
   63242.0,
   98315.0,
   104471.0,
   43222.0,
   86269.0,
   237875.0,
   120715.0,
   91771.0,
   282335.0,
   48516.0,
   206414.0,
   62995.0,
   69301.0,
   75248.0,
   247962.0,
   65727.0,
   232895.0,
   210455.0,
   175391.0,
   206839.0,
   217359.0,
   182542.0,
   67486.0,
   176831.0,
   98788.0,
   209794.0,
   84530.0,
   219924.0,
   155358.0,
   78518.0,
   231368.0,
   153673.0,
   129483.0,
   135129.0,
   130344.0,
   172716.0,
   107742.0,
   233664.0,
   93279.0,
   100507.0,
   173914.0,
   217921.0,
   361382.0,
   168013.0,
   239755.0,
   164603.0,
   181063.0,
   181833.0,
   57159.0,
   145910.0,
   107421.0,
   141118.0,
   163957.0,
   155762.0,
   210946.0,
   175000.0,
   185684.0,
   150305.0,
   162473.0,
   218677.0,
   81930.0,

### Reduce Function Interpretation
The 'functools.reduce()' function combines the partial results from all chunks into one final grouped dataset. This simulates the final aggregation stage in a distributed system, where results from different workers are merged before producing the final output.

In [15]:
#Calculate final average salary per occupation after combining all chunks
chunk_average_salary = {
    occupation: sum(salaries) / len(salaries)
    for occupation, salaries in final_grouped_data.items()
}
#sort results by average salary in descending order
chunk_sorted_results = sorted(chunk_average_salary.items(), key=lambda x: x[1], reverse=True)
chunk_sorted_results[:10]

[('AI Engineer', 252158.15810768752),
 ('Product Manager', 251276.937323708),
 ('Cloud Engineer', 242826.7555763195),
 ('Data Scientist', 233261.97111748127),
 ('Software Engineer', 223677.86047125445),
 ('Operations Manager', 213451.235518732),
 ('Financial Analyst', 202585.41912186722),
 ('UX Designer', 192173.97958988577),
 ('Business Analyst', 191619.7314657886),
 ('Data Analyst', 179691.18065597318)]

### Chunk-Based Mapreduce Results Interpretation
After combining all chunks using 'functools.reduce()', the final average salary was calculated for each occupation. The results confirm that the chunk-based MapReduce simulation produces the same type of output as the original MapReduce process, while better representing how distributed systems process large datasets.

### Parallelization Explanation
In a real Big Data environment, the dataset would be divided into smaller chunks and processed across multiple machines. Each machine would apply the mapper function to its assigned chunk and create local grouped results. Then, the system would shuffle and merge results with the same key. Finally, reducers would calculate the final average salary for each occupation.

As the dataset becomes larger, parallel processing improves performance because multiple chunks can be processed at the same time instead of processing the entire dataset on one machine.

## Part 2: **Apache Spark Workflow**
In this section, Apache Spark is used to process and analyze the dataset efficiently. Spark allows large-scale data processing using distributed computing and DataFrames.
We will perform data filtering, transformation, aggregation and analysis using PySpark.

In [16]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("Job Market Analysis").getOrCreate()
print("Spark session created successfully.")

Spark session created successfully.

In [17]:
#load the csv file into a Spark DataFrame
spark_df = spark.read.csv(
    file_path,
    header=True,
    inferSchema=True
)
spark_df.show(5)

+-------------+---------+------------------+---------------+-------------------+--------+---------------+---------------+------+------------+----+-----+
|      country|     city|        occupation|          field|years_of_experience|  salary|employment_type|education_level|gender|company_size|year|month|
+-------------+---------+------------------+---------------+-------------------+--------+---------------+---------------+------+------------+----+-----+
|  Switzerland|   Zurich|Operations Manager|     Operations|                 16|359609.0| work_from_home|         Master|  Male|       Large|2023|    8|
|        India|Bangalore|        HR Analyst|Human Resources|                 12| 79059.0|      part_time|            PhD|  Male|       Large|2023|    5|
|       Sweden|Stockholm| Software Engineer|     Technology|                 10|258077.0|      freelance|         Master|  Male|  Enterprise|2023|    9|
|  South Korea|    Seoul|Operations Manager|     Operations|                  7|252282.0|      part_time|         Master|Female|       Large|2024|   12|
|United States| New York|    Cloud Engineer|     Technology|                  4|330618.0|      part_time|         Master|  Male|  Enterprise|2022|    1|
+-------------+---------+------------------+---------------+-------------------+--------+---------------+---------------+------+------------+----+-----+
only showing top 5 rows

### Spark Data Loading Interpretation
The dataset was loaded into a Spark DataFrame. Using Spark DataFrames allows the data to be processed efficiently in a distributed environment, which is important for large datasets.

In [18]:
#display the schema of the Spark DataFrame
spark_df.printSchema()
#count rows and columns
row_count = spark_df.count()
column_count = len(spark_df.columns)
print("Number of rows:", row_count)
print("Number of columns:", column_count)

root
 |-- country: string (nullable = true)
 |-- city: string (nullable = true)
 |-- occupation: string (nullable = true)
 |-- field: string (nullable = true)
 |-- years_of_experience: integer (nullable = true)
 |-- salary: double (nullable = true)
 |-- employment_type: string (nullable = true)
 |-- education_level: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- company_size: string (nullable = true)
 |-- year: integer (nullable = true)
 |-- month: integer (nullable = true)

Number of rows: 500000
Number of columns: 12

### Spark Data Understanding Interpretation
The schema shows that the dataset contains a mix of categorical and numerical features. Categorical variables include columns such as country, city, occupation, field, employment type, education level, gender and company size. Numerical variables include years of experience, salary, year and month.

All columns are marked as nullable, meaning they can contain missing values, although earlier inspection showed no missing data. The dataset contains 500,000 rows and 12 columns, confirming that is large enough to require efficient processing using Spark.

### **Data Filtering**
In this step, we filter the dataset to focus on high-paying jobs. This helps us analyze patterns among higher salary roles and identify which occupations and conditions are associated with better compensation.

In [19]:
#filter jobs with salary greater than 200,000
high_salary_df = spark_df.filter(spark_df.salary > 200000)
high_salary_df.show(5)
print("Number of high-paying jobs:", high_salary_df.count())

+--------------------+---------+------------------+----------+-------------------+--------+---------------+---------------+------+------------+----+-----+
|             country|     city|        occupation|     field|years_of_experience|  salary|employment_type|education_level|gender|company_size|year|month|
+--------------------+---------+------------------+----------+-------------------+--------+---------------+---------------+------+------------+----+-----+
|         Switzerland|   Zurich|Operations Manager|Operations|                 16|359609.0| work_from_home|         Master|  Male|       Large|2023|    8|
|              Sweden|Stockholm| Software Engineer|Technology|                 10|258077.0|      freelance|         Master|  Male|  Enterprise|2023|    9|
|         South Korea|    Seoul|Operations Manager|Operations|                  7|252282.0|      part_time|         Master|Female|       Large|2024|   12|
|       United States| New York|    Cloud Engineer|Technology|                  4|330618.0|      part_time|         Master|  Male|  Enterprise|2022|    1|
|United Arab Emirates|    Dubai|  Business Analyst|  Business|                  5|211953.0|      freelance|         Master|  Male|      Medium|2023|    1|
+--------------------+---------+------------------+----------+-------------------+--------+---------------+---------------+------+------------+----+-----+
only showing top 5 rows
Number of high-paying jobs: 250511

### Filtering Interpretation
The filtered dataset shows that a significant portion of jobs (250,511 out of 500,000) have salaries above 200,000, indicating that high-paying roles are relatively common in this dataset. From the sample output, high-paying jobs are observed across different countries such as Switzerland, Sweden, the United States and the United Arab Emirates, suggesting that high salaries are not limited to a signle region but are globally distributed.

These roles are often associated with mid to high levels of experience (4 and 16 years years), indicating that experience plays a key role in achieving higher salaries.

Additionally, many of these positions are in fields like "Technology" and "Operations", reinforcing the idea that technical and managerial roles tend to offer higher compensation.

### **Column Selection**
In this step, we select only the most relevant columns for analysis. Focusing on key features such as occupation, salary, years of experience, level of education and country helps simplify the dataset and improves processing efficiency while keeping the most important information for analysis.

In [20]:
#select important columns for analysis
selected_df = spark_df.select(
    "occupation",
    "salary",
    "years_of_experience",
    "country",
    "education_level"
)
selected_df.show(5)

+------------------+--------+-------------------+-------------+---------------+
|        occupation|  salary|years_of_experience|      country|education_level|
+------------------+--------+-------------------+-------------+---------------+
|Operations Manager|359609.0|                 16|  Switzerland|         Master|
|        HR Analyst| 79059.0|                 12|        India|            PhD|
| Software Engineer|258077.0|                 10|       Sweden|         Master|
|Operations Manager|252282.0|                  7|  South Korea|         Master|
|    Cloud Engineer|330618.0|                  4|United States|         Master|
+------------------+--------+-------------------+-------------+---------------+
only showing top 5 rows

### Column Selection Interpretation
The dataset has been refined to include the most relevant features for salary analysis.
* Occupation helps identify high-paying roles.
* Salary is the main variable of interest.
* Years of experience allows analysis of how experience influences income.
* Country provides insight into geographical salary differences.
* Education level adds another important dimension, enabling analysis of how academic qualifications impact salary.

### Feature Engineering: Salary Category
In this step, a new feature called 'salary_category' is created. This categorizes saalries into three groups: Low, Medium and High. This transormation simplifies analysis and helps identify patterns more easily across different salary levels.

In [21]:
from pyspark.sql.functions import when
enhanced_df = selected_df.withColumn(
    "salary_category",
    when(selected_df.salary < 100000, "Low")
    .when((selected_df.salary >= 100000) & (selected_df.salary < 200000), "Medium")
    .otherwise("High")
)
enhanced_df.show(5)

+------------------+--------+-------------------+-------------+---------------+---------------+
|        occupation|  salary|years_of_experience|      country|education_level|salary_category|
+------------------+--------+-------------------+-------------+---------------+---------------+
|Operations Manager|359609.0|                 16|  Switzerland|         Master|           High|
|        HR Analyst| 79059.0|                 12|        India|            PhD|            Low|
| Software Engineer|258077.0|                 10|       Sweden|         Master|           High|
|Operations Manager|252282.0|                  7|  South Korea|         Master|           High|
|    Cloud Engineer|330618.0|                  4|United States|         Master|           High|
+------------------+--------+-------------------+-------------+---------------+---------------+
only showing top 5 rows

In [22]:
#Count how many jobs per salary category
enhanced_df.groupBy("salary_category").count().show()

+---------------+------+
|salary_category| count|
+---------------+------+
|           High|250514|
|            Low| 51259|
|         Medium|198227|
+---------------+------+

### Salary Category Interpretation
The distribution of jobs across salary categories shows that high-paying jobs dominate the dataset with 250,514 positions classified as "High". Medium-paying jobs follow with 198,227 entries while low-paying jobs are significantly fewer at 51,259.
This indicates that the dataset is skewed toward higher salary ranges, suggesting that many roles in this dataset offer competitive compensation.

Overall, this distribution highlights that a large portion of the job market in this dataset is concentrated in medium to high salary ranges, reinforcing the importance of experience, skills and specialization in achieving higher pay.

### Feature Engineering: Experience Level
In this step, a new feature called 'experience_level' is created. This categorizes professionals into Junior, Mid and Senior levels based on their years of experience. This helps simplify analysis and allows us to better understand how experience impacts salary.

In [23]:
from pyspark.sql.functions import when
enhanced_df = enhanced_df.withColumn(
    "experience_level",
    when(enhanced_df.years_of_experience < 3, "Junior")
    .when((enhanced_df.years_of_experience >= 3) & (enhanced_df.years_of_experience < 10), "Mid")
    .otherwise("Senior")
)
enhanced_df.show(5)

+------------------+--------+-------------------+-------------+---------------+---------------+----------------+
|        occupation|  salary|years_of_experience|      country|education_level|salary_category|experience_level|
+------------------+--------+-------------------+-------------+---------------+---------------+----------------+
|Operations Manager|359609.0|                 16|  Switzerland|         Master|           High|          Senior|
|        HR Analyst| 79059.0|                 12|        India|            PhD|            Low|          Senior|
| Software Engineer|258077.0|                 10|       Sweden|         Master|           High|          Senior|
|Operations Manager|252282.0|                  7|  South Korea|         Master|           High|             Mid|
|    Cloud Engineer|330618.0|                  4|United States|         Master|           High|             Mid|
+------------------+--------+-------------------+-------------+---------------+---------------+----------------+
only showing top 5 rows

In [24]:
#Count how many jobs per experience level
enhanced_df.groupBy("experience_level").count().show()

+----------------+------+
|experience_level| count|
+----------------+------+
|          Senior|297234|
|             Mid|141849|
|          Junior| 60917|
+----------------+------+

### Experience Level Interpretation
The distribution of jobs across experience levels shows a clear imbalnce. Senior-level positions dominate the dataset with 297,234 jobs, followed by Mid-level roles with 141,849 jobs while Junior positions are significantly fewer at 60,917.

This suggests that the job market represented in this dataset is heavily skewed toward experienced professionals indicating that higher experience is more in demand. Additionally, since senior roles are the majority, it is liekly that a large portion of high-apying jobs are associated with higher experience levels.

This insight highlights the strong relationship between experience and job availability and suggests that career progression plays a key role in accessing more opportunities and higher salaries.

### **Advanced Operations**

### Basic Aggregation: Average Salary by Occupation
This analysis calculates the average salary for each occupation to identify the highest-paying job roles.

In [25]:
from pyspark.sql.functions import avg
avg_salary_job = enhanced_df.groupBy("occupation").agg(avg("salary").alias("avg_salary")).orderBy("avg_salary", ascending=False)
avg_salary_job.show(10)

+------------------+------------------+
|        occupation|        avg_salary|
+------------------+------------------+
|       AI Engineer|252158.15810768752|
|   Product Manager|  251276.937323708|
|    Cloud Engineer| 242826.7555763195|
|    Data Scientist|233261.97111748127|
| Software Engineer|223677.86047125445|
|Operations Manager|  213451.235518732|
| Financial Analyst|202585.41912186722|
|       UX Designer|192173.97958988577|
|  Business Analyst| 191619.7314657886|
|      Data Analyst|179691.18065597318|
+------------------+------------------+
only showing top 10 rows

### Occupation-Based Salary Interpretation
The result show that the highest average salaries are concentrated in technical and leadership roles. AI Engineer and Product Manager are the top-paying occupations, both exceeding 250,000 in average salary. Other high-paying roles include Cloud Engineer, Data Scientist and Software Engineer which are all part of the technology sector. This indicates that jobs related to advanced technologies, data and cloud computing are among the most financially rewarding. Additionally, management roles such as Product Manager and Operations Manager also rank highly, suggesting that leadership and strategic responsibilities are strongly linked to higher compensation.

Overall, this analysis demonstrates that both technical expertise and managerial responsibility play a key role in achieving higher salaries in the job market.

While average salary provides a general overview, it does not capture the full distribution of salaries.  
Therefore, we extend the analysis by including minimum, maximum, and job count to gain deeper insights.

### Advanced Aggregation: Salary Distribution by Occupation
In this step, we compute multiple statistics for each occupation including,
* Average salary
* Minimum salary
* Maximum salary
* Number of jobs
This provides a more comprehensive understanding of salary distribution across different roles.

In [26]:
from pyspark.sql.functions import avg, min, max, count
salary_stats_job = enhanced_df.groupBy("occupation").agg(
    avg("salary").alias("avg_salary"),
    min("salary").alias("min_salary"),
    max("salary").alias("max_salary"),
    count("*").alias("job_count")).orderBy("avg_salary", ascending=False)
salary_stats_job.show(10)

+------------------+------------------+----------+----------+---------+
|        occupation|        avg_salary|min_salary|max_salary|job_count|
+------------------+------------------+----------+----------+---------+
|       AI Engineer|252158.15810768752|   12000.0|  370000.0|    41769|
|   Product Manager|  251276.937323708|   12000.0|  370000.0|    41834|
|    Cloud Engineer| 242826.7555763195|   12237.0|  370000.0|    41739|
|    Data Scientist|233261.97111748127|   12000.0|  370000.0|    41513|
| Software Engineer|223677.86047125445|   12247.0|  370000.0|    41676|
|Operations Manager|  213451.235518732|   12000.0|  370000.0|    41640|
| Financial Analyst|202585.41912186722|   12000.0|  370000.0|    41816|
|       UX Designer|192173.97958988577|   12000.0|  370000.0|    41842|
|  Business Analyst| 191619.7314657886|   12215.0|  370000.0|    41302|
|      Data Analyst|179691.18065597318|   12000.0|  370000.0|    41770|
+------------------+------------------+----------+----------+---------+
only showing top 10 rows

### Advanced Aggregation Interpretation
The results provide a comprehensive view of salary distribution across different occupations.
AI Engineer and Product Manager remain the highest-paying roles based on average salary, confirming that both advanced technical expertise and managerial responsibility are highly valued in the job market.
Although all occupations share a similar maximum salary (370,000), the differences in average salary indicate that higher-paying roles are more consistently compensated at elevated levels.  
The wide gap between minimum and maximum salaries across all occupations highlights significant salary variability. This suggests that factors such as experience, company size, and geographic location strongly influence earnings within the same role.
Additionally, the job_count values are relatively similar across occupations, indicating that these roles are comparably represented in the dataset. This allows for fair comparison between them without bias from uneven sample sizes.

Overall, this analysis shows that while many roles can reach high salary levels, occupations in technology and management are more likely to consistently offer higher compensation.

### Salary by Education and Experience Level
This analysis examines how salary varies based on both education level and experience level. By combining these two factors, we can better understand how academic qualifications and professional experience interact to influence salary.

In [27]:
from pyspark.sql.functions import avg
salary_edu_exp = enhanced_df.groupBy("education_level", "experience_level").agg(avg("salary").alias("avg_salary")).orderBy("education_level", "experience_level")
salary_edu_exp.show()

+---------------+----------------+------------------+
|education_level|experience_level|        avg_salary|
+---------------+----------------+------------------+
|       Bachelor|          Junior|116692.32593982443|
|       Bachelor|             Mid| 181513.1514817951|
|       Bachelor|          Senior|217343.16443982112|
|    High School|          Junior|100459.41348212548|
|    High School|             Mid| 154986.9853003176|
|    High School|          Senior| 186949.5215383787|
|         Master|          Junior| 134466.0605981625|
|         Master|             Mid|207510.01371976882|
|         Master|          Senior|245848.50996327898|
|            PhD|          Junior| 149557.3763292635|
|            PhD|             Mid|231356.02446161714|
|            PhD|          Senior| 269948.5978090976|
+---------------+----------------+------------------+

In [28]:
salary_edu_exp.orderBy("avg_salary", ascending=False).show()

+---------------+----------------+------------------+
|education_level|experience_level|        avg_salary|
+---------------+----------------+------------------+
|            PhD|          Senior| 269948.5978090976|
|         Master|          Senior|245848.50996327898|
|            PhD|             Mid|231356.02446161714|
|       Bachelor|          Senior|217343.16443982112|
|         Master|             Mid|207510.01371976882|
|    High School|          Senior| 186949.5215383787|
|       Bachelor|             Mid| 181513.1514817951|
|    High School|             Mid| 154986.9853003176|
|            PhD|          Junior| 149557.3763292635|
|         Master|          Junior| 134466.0605981625|
|       Bachelor|          Junior|116692.32593982443|
|    High School|          Junior|100459.41348212548|
+---------------+----------------+------------------+

### Education and Experience-Based Salary Interpretation
The results have a clear relationship between both education level and experience level in determining salary. Across all education levels, salaries consistently increase from Junior to Mid to Senior positions, confirming that experience is a strong and reliable driver of income. At the same time, education level also plays a significant role. For each experience level, individuals with higher degrees tend to earn more. The highest overall salaries are observed among Senior professionals with advanced degrees, particularly PhDs and Master's degrees, indicating that the combination of high experience and advanced education leads to the greatest earning potential.
However, at lower experience levels, the differences between education levels are less pronounced, suggesting that early in a career, experience may matter more than education.

Overall, this analysis highlights that while both education and experience influence salary, experience has a more consistent impact while education provides an additional advantage especially at higher career levels.

### **Exploratory Data Analysis (EDA)**
In this section, we explore general patterns in the dataset to better understand the job market distribution.

In [29]:
from pyspark.sql.functions import count
top_countries = enhanced_df.groupBy("country").agg(count("*").alias("job_count")).orderBy("job_count", ascending=False)
top_countries.show(10)

+--------------+---------+
|       country|job_count|
+--------------+---------+
| United States|    45238|
|        Brazil|    23010|
|         Italy|    22971|
|        Mexico|    22964|
|       Ireland|    22959|
|United Kingdom|    22871|
|         Spain|    22839|
|       Germany|    22838|
|        Sweden|    22793|
|        Canada|    22769|
+--------------+---------+
only showing top 10 rows

### Country-Based Job Distribution Interpretation
The results show that the United States has the highest number of job entries in the dataset, significantly exceeding other countries.
Other countries such as Brazil, Italy, Mexico, and Ireland also have high job counts, but at a noticeably lower level compared to the United States.
This suggests that the dataset is somewhat dominated by job listings from the United States, which may indicate either a stronger job market presence or a data collection bias toward that region.
Additionally, the relatively similar job counts among several European and Latin American countries suggest a more balanced distribution of opportunities outside the top country.

Overall, this analysis highlights geographical differences in job availability and suggests that regional factors may influence job distribution in the dataset.

In [30]:
enhanced_df.describe().show()

+-------+-----------+-----------------+-------------------+-------------+---------------+---------------+----------------+
|summary| occupation|           salary|years_of_experience|      country|education_level|salary_category|experience_level|
+-------+-----------+-----------------+-------------------+-------------+---------------+---------------+----------------+
|  count|     500000|           500000|             500000|       500000|         500000|         500000|          500000|
|   mean|       NULL|    207019.212078|          11.865168|         NULL|           NULL|           NULL|            NULL|
| stddev|       NULL|85867.30737286204|  7.178829110861335|         NULL|           NULL|           NULL|            NULL|
|    min|AI Engineer|          12000.0|                  0|    Australia|       Bachelor|           High|          Junior|
|    max|UX Designer|         370000.0|                 25|United States|            PhD|         Medium|          Senior|
+-------+-----------+-----------------+-------------------+-------------+---------------+---------------+----------------+

### Summary Statistics Interpretation
The summary statistics provide an overview of the dataset, including mean, minimum, and maximum values.
The average salary is relatively high, confirming that the dataset is skewed toward well-compensated roles.  
The wide range between minimum and maximum salaries indicates significant variability in income across different jobs and experience levels.

### **Optimization:** Column Reduction
In Big Data processing, it is important to reduce the size of the dataset by removing unnecessary columns.
This improves performance and reduces memory usage, especially when working with large datasets.

In [31]:
optimized_df = enhanced_df.select(
    "occupation",
    "salary",
    "experience_level",
    "education_level",
    "salary_category"
)
optimized_df.show(5)

+------------------+--------+----------------+---------------+---------------+
|        occupation|  salary|experience_level|education_level|salary_category|
+------------------+--------+----------------+---------------+---------------+
|Operations Manager|359609.0|          Senior|         Master|           High|
|        HR Analyst| 79059.0|          Senior|            PhD|            Low|
| Software Engineer|258077.0|          Senior|         Master|           High|
|Operations Manager|252282.0|             Mid|         Master|           High|
|    Cloud Engineer|330618.0|             Mid|         Master|           High|
+------------------+--------+----------------+---------------+---------------+
only showing top 5 rows

### Optimization Interpretation
Reducing the number of columns helps improve performance when processing large datasets.
By keeping only the relevant features, we reduce memory usage and make computations faster.  
This is especially important in Big Data environments where datasets can contain millions of rows and many unnecessary attributes.
Column reduction ensures that only useful data is processed, which improves efficiency and scalability of the analysis.

### **Machine Learning Preparation**
The dataset is split into training and testing sets to prepare it for potential machine learning applications.

In [32]:
#split dataset into training (80%) and testing (20%)
train_df, test_df = enhanced_df.randomSplit([0.8, 0.2], seed=42)
print("Training set size:", train_df.count())
print("Testing set size:", test_df.count())

Training set size: 399788
Testing set size: 100212

### Train/Test Split Interpretation
The dataset was successfully divided into training and testing sets, with approximately 80% of the data (399,788 records) used for training and 20% (100,212 records) used for testing.
This balanced split ensures that the training set is large enough to learn meaningful patterns, while the testing set remains sufficiently representative for evaluating model performance.

This preparation is important in Big Data contexts, where large datasets are commonly used to build and validate scalable machine learning models.

## Part 3: **Final Analysis and Discussion**

### Key Insights
The analysis revealed several important patterns in the job market dataset.
First, salaries are strongly influenced by occupation. Technical roles such as AI Engineer, Cloud Engineer, and Data Scientist consistently offer higher average salaries compared to other roles.
Second, experience plays a critical role in salary growth. Salaries increase significantly from Junior to Senior levels, showing that career progression is a major factor in earning potential.
Third, education also impacts salary, particularly at higher experience levels. Individuals with advanced degrees such as Master's and PhD tend to earn more, especially in senior positions.
Finally, the dataset shows a concentration of high-paying jobs, indicating that many roles represented require specialized skills or experience.

---

### Limitations of the Analysis
Despite these insights, there are several limitations.
The dataset may contain bias, as certain countries (such as the United States) are overrepresented. This may affect the generalizability of the results.
Additionally, the analysis does not include other important factors that influence salary, such as specific skills, company reputation, or industry demand.
Another limitation is that salary ranges were simplified into categories, which may reduce the precision of the analysis.

---

### Scalability in a Big Data Context
The solution is designed to scale effectively in a real-world Big Data environment.
The use of MapReduce demonstrates how large datasets can be processed in parallel by dividing data into chunks and aggregating results efficiently.
Apache Spark further improves scalability by enabling distributed data processing, in-memory computation, and optimized query execution.
Techniques such as column reduction improve performance and reduce memory usage, which is essential when working with large-scale datasets.
Overall, the approach used in this project can handle much larger datasets and can be extended to real-world Big Data applications.